### ISSUE TITLE
Faraday/SSL Error "unable to get local issuer certificate" when running example in #1 

### ISSUE THREAD

**Issue by leandrosardi** [leandrosardi/my-gmass#2]
```
C:\code2\mysaas\extensions\my-gmass>ruby example.rb
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/googleauth-1.2.0/lib/googleauth/credentials_loader.rb:157: warning: cannot close fd before spawn
Open the following URL in the browser and enter the resulting code after authorization:
https://accounts.google.com/o/oauth2/auth?access_type=offline&approval_prompt=force&client_id=501400680581-5lanv9qch1594sh2l7md09iqg4ot5oqg.apps.googleusercontent.com&include_granted_scopes=true&redirect_uri=urn:ietf:wg:oauth:2.0:oob&response_type=code&scope=https://www.googleapis.com/auth/gmail.readonly

C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/googleauth-1.2.0/lib/googleauth/credentials_loader.rb:157: warning: cannot close fd before spawn
C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/googleauth-1.2.0/lib/googleauth/signet.rb:112:in `rescue in retry_with_error': Unexpected error: #<Faraday::SSLError wrapped=#<OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 peeraddr=172.217.172.74:443 state=error: certificate verify failed (unable to get local issuer certificate)>> (Signet::AuthorizationError)
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/googleauth-1.2.0/lib/googleauth/signet.rb:101:in `retry_with_error'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/googleauth-1.2.0/lib/googleauth/signet.rb:74:in `fetch_access_token!'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/googleauth-1.2.0/lib/googleauth/user_authorizer.rb:161:in `get_credentials_from_code'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/googleauth-1.2.0/lib/googleauth/user_authorizer.rb:183:in `get_and_store_credentials_from_code'
        from example.rb:32:in `authorize'
        from example.rb:42:in `<main>'
C:/Ruby31-x64/lib/ruby/3.1.0/net/protocol.rb:46:in `connect_nonblock': SSL_connect returned=1 errno=0 peeraddr=172.217.172.74:443 state=error: certificate verify failed (unable to get local issuer certificate) (Faraday::SSLError)
        from C:/Ruby31-x64/lib/ruby/3.1.0/net/protocol.rb:46:in `ssl_socket_connect'
        from C:/Ruby31-x64/lib/ruby/3.1.0/net/http.rb:1048:in `connect'
        from C:/Ruby31-x64/lib/ruby/3.1.0/net/http.rb:976:in `do_start'
        from C:/Ruby31-x64/lib/ruby/3.1.0/net/http.rb:965:in `start'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/faraday-net_http-2.0.3/lib/faraday/adapter/net_http.rb:145:in `request_via_request_method'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/faraday-net_http-2.0.3/lib/faraday/adapter/net_http.rb:130:in `request_with_wrapped_block'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/faraday-net_http-2.0.3/lib/faraday/adapter/net_http.rb:121:in `perform_request'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/faraday-net_http-2.0.3/lib/faraday/adapter/net_http.rb:66:in `block in call'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/faraday-2.3.0/lib/faraday/adapter.rb:45:in `connection'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/faraday-net_http-2.0.3/lib/faraday/adapter/net_http.rb:65:in `call'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/faraday-2.3.0/lib/faraday/request/url_encoded.rb:25:in `call'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/faraday-2.3.0/lib/faraday/rack_builder.rb:153:in `build_response'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/faraday-2.3.0/lib/faraday/connection.rb:445:in `run_request'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/faraday-2.3.0/lib/faraday/connection.rb:281:in `post'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/signet-0.17.0/lib/signet/oauth_2/client.rb:1005:in `fetch_access_token'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/signet-0.17.0/lib/signet/oauth_2/client.rb:1039:in `fetch_access_token!'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/googleauth-1.2.0/lib/googleauth/signet.rb:75:in `block in fetch_access_token!'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/googleauth-1.2.0/lib/googleauth/signet.rb:102:in `retry_with_error'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/googleauth-1.2.0/lib/googleauth/signet.rb:74:in `fetch_access_token!'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/googleauth-1.2.0/lib/googleauth/user_authorizer.rb:161:in `get_credentials_from_code'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/googleauth-1.2.0/lib/googleauth/user_authorizer.rb:183:in `get_and_store_credentials_from_code'
        from example.rb:32:in `authorize'
        from example.rb:42:in `<main>'
C:/Ruby31-x64/lib/ruby/3.1.0/net/protocol.rb:46:in `connect_nonblock': SSL_connect returned=1 errno=0 peeraddr=172.217.172.74:443 state=error: certificate verify failed (unable to get local issuer certificate) (OpenSSL::SSL::SSLError)
        from C:/Ruby31-x64/lib/ruby/3.1.0/net/protocol.rb:46:in `ssl_socket_connect'
        from C:/Ruby31-x64/lib/ruby/3.1.0/net/http.rb:1048:in `connect'
        from C:/Ruby31-x64/lib/ruby/3.1.0/net/http.rb:976:in `do_start'
        from C:/Ruby31-x64/lib/ruby/3.1.0/net/http.rb:965:in `start'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/faraday-net_http-2.0.3/lib/faraday/adapter/net_http.rb:145:in `request_via_request_method'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/faraday-net_http-2.0.3/lib/faraday/adapter/net_http.rb:130:in `request_with_wrapped_block'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/faraday-net_http-2.0.3/lib/faraday/adapter/net_http.rb:121:in `perform_request'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/faraday-net_http-2.0.3/lib/faraday/adapter/net_http.rb:66:in `block in call'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/faraday-2.3.0/lib/faraday/adapter.rb:45:in `connection'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/faraday-net_http-2.0.3/lib/faraday/adapter/net_http.rb:65:in `call'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/faraday-2.3.0/lib/faraday/request/url_encoded.rb:25:in `call'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/faraday-2.3.0/lib/faraday/rack_builder.rb:153:in `build_response'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/faraday-2.3.0/lib/faraday/connection.rb:445:in `run_request'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/faraday-2.3.0/lib/faraday/connection.rb:281:in `post'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/signet-0.17.0/lib/signet/oauth_2/client.rb:1005:in `fetch_access_token'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/signet-0.17.0/lib/signet/oauth_2/client.rb:1039:in `fetch_access_token!'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/googleauth-1.2.0/lib/googleauth/signet.rb:75:in `block in fetch_access_token!'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/googleauth-1.2.0/lib/googleauth/signet.rb:102:in `retry_with_error'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/googleauth-1.2.0/lib/googleauth/signet.rb:74:in `fetch_access_token!'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/googleauth-1.2.0/lib/googleauth/user_authorizer.rb:161:in `get_credentials_from_code'
        from C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/googleauth-1.2.0/lib/googleauth/user_authorizer.rb:183:in `get_and_store_credentials_from_code'
        from example.rb:32:in `authorize'
        from example.rb:42:in `<main>'
```

**Comment by leandrosardi** [comment]
Try if the same error happens on Linux, after install environment following this tutorial: 
https://github.com/leandrosardi/mysaas/issues/16

**Comment by leandrosardi** [comment]
Working with no issue on Linux.
